01-Sep-2020 18:52:33.773 信息 [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
01-Sep-2020 18:52:33.773 信息 [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
01-Sep-2020 18:52:33.789 信息 [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@ff3cfb')
01-Sep-2020 18:55:28.619 严重 [http-nio-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke 在路径为[/App]的上下文中，servlet[MyServlet_03]的Servlet.service()引发异常
	org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
		at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
		at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
		at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
		at bean.SelectSpring.selectImpl(SelectSpring.java:31)
		at servlet.MyServlet_03.doPost(MyServlet_03.java:33)
		at servlet.MyServlet_03.doGet(MyServlet_03.java:19)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
		at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
		at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
		at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
		at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
		... 30 more
	Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
		at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
		at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
		at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
		... 35 more
01-Sep-2020 18:55:40.136 严重 [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke 在路径为[/App]的上下文中，servlet[MyServlet_03]的Servlet.service()引发异常
	org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
		at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
		at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
		at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
		at bean.SelectSpring.selectImpl(SelectSpring.java:31)
		at servlet.MyServlet_03.doPost(MyServlet_03.java:33)
		at servlet.MyServlet_03.doGet(MyServlet_03.java:19)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
		at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
		at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
		at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
		at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
		... 30 more
	Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
		at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
		at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
		at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
		... 35 more
01-Sep-2020 18:57:12.368 信息 [Thread-4] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
01-Sep-2020 18:57:12.368 信息 [Thread-4] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
01-Sep-2020 19:07:11.585 信息 [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
01-Sep-2020 19:07:11.585 信息 [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
01-Sep-2020 19:07:11.585 信息 [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@1abd01')
01-Sep-2020 19:08:22.992 严重 [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke 在路径为[/App]的上下文中，servlet[MyServlet_02]的Servlet.service()引发异常
	org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
		at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
		at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
		at bean.InsertSpring.insert(InsertSpring.java:17)
		at servlet.MyServlet_02.doPost(MyServlet_02.java:33)
		at servlet.MyServlet_02.doGet(MyServlet_02.java:17)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
		at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
		at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
		at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
		at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
		... 29 more
	Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
		at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
		at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
		at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
		at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
		... 34 more
01-Sep-2020 19:14:02.640 信息 [Thread-4] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
01-Sep-2020 19:14:02.640 信息 [Thread-4] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
